# Generated by Django 4.1.3 on 2022-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('foodtype', models.CharField(max_length=15, null=True)),
                ('ingredients', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
